:linkattrs:
:source-highlighter: rouge


== Technical overview ==


=== simpl4 backend, the main ingredients ===

[.width800]
imagezoom::docu/images/overview/bigpicture.svg[]



=== Service ===

A service consists of one more building blocks.

[.width800]
imagezoom::docu/images/overview/service.svg[]

==== Exchange ====

On the service entrypoint an exchange is created and with the service parameters populated. +
The exchange is handed from building block to building block.

[.width500]
imagezoom::docu/images/overview/exchange.svg[]



=== Activiti processengine

* Processes (workflows) are executed in the Activiti processengine.
* The processes are specified in BPMN2.
* A graphical editor (Modeler) is available here.
* Service tasks are delegated to the service engine.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registered by IANA
* Provides routed remote procedure calls (RPC) and PubSub
* WAMP consists of clients and routers (not be confused with the Camel routes)
* The procedures are registered on the router
* *simpl4* is WAMP client and router
* External equipment (or browsers) can register their services (procedures) and thereby are reachable from each other WAMP client. +
Incidentally, in this way is browser-browser communication possible!

=== Standalone server ===

[.width700]
imagezoom::docu/images/overview/server_en.svg[]
