:linkattrs:
:source-highlighter: rouge


== Technical overview ==


=== simpl4 backend, the main ingredients ===

[.width800]
imagezoom::docu/images/overview/bigpicture.svg[]



=== Service ===

A service consists of one or more building blocks.

[.width800]
imagezoom::docu/images/overview/service.svg[]

==== Exchange and message ====

On the service entrypoint an exchange is created and with the service parameters populated. +
The exchange is handed from building block to building block. +
An exchange in simpl4 is the message container during the processing. +

Properties are used to contain global-level information, +
whereas message headers are specific to a particular message. +
Properties are name-value pairs; the name is a unique, case-insensitive string.  +
Simpl4 imposes no constraints on the type of the value. You can store a any data.

The message containing the data.
Wherein the body contains the payload and the the headers the meta data. +
If a building block has the concept of headers,for example, http oder jms, the message headers are +
converted to/from protocol specific headers.

[.width500]
imagezoom::docu/images/overview/exchange.svg[]



=== Activiti processengine

* Processes (workflows) are executed in the Activiti processengine.
* The processes are specified in BPMN2.
* A graphical editor (Modeler) is available here.
* Service tasks are delegated to the service engine.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registered by IANA
* Provides routed remote procedure calls (RPC) and PubSub
* WAMP consists of clients and routers (not be confused with the Camel routes)
* The procedures are registered on the router
* *simpl4* is WAMP client and router
* External equipment (or browsers) can register their services (procedures) and thereby are reachable from each other WAMP client. +
Incidentally, in this way is browser-browser communication possible!

=== Standalone server ===

[.width700]
imagezoom::docu/images/overview/server_en.svg[]
