:linkattrs:
:source-highlighter: rouge


== Technischer Überblick ==


=== simpl4 backend, die wichtigsten Bestandteile ===

[.width800]
imagezoom::web/presentation/images/bigpicture.svg[]

=== Apache Camel *Routing und Konvertierungs Engine* ===

* Camelrouten sind die hauptsächlichen Verarbeitungseinheiten in *_simpl4._* +
Sie spezifizieren den Datenfluß von Komponente zu Komponente. +
Eine Camelroute entspricht einer Prozedur die sich am WAMP Router registriert und via RPC(HTTP oder Websocket) erreichbar ist.

=== Activiti Prozessengine ===

* Prozesse(Workflows) werden in der activiti prozessengine ausgeführt.
* Die Prozesse werden in BPMN2 spezifiziert.
* Ein graphischer Editor(Modeler) steht hier zur Verfügung.
* Serviceaufgaben können an Camel delegiert werden.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registriert bei der IANA
* Bietet geroutete Remote-Procedure-Calls (RPC) und PubSub
* WAMP besteht aus Clients und Routern (Nicht verwechseln mit den Camelrouten)
* Am Router sind die Prozeduren registriert
* *simpl4* ist WAMP-Client und WAMP-Router
* Es können sich externe Geräte (oder auch Browser) ihre Dienste (Prozeduren) registrieren lassen, und sind damit von jedem anderen WAMP-Client erreichbar. +
Positiver Nebeneffekt, dadurch ist Browser-to-Browser Kommunikation möglich!


=== Standalone-Server ===

[.width700]
imagezoom::web/presentation/images/server_en.svg[]

=== Servlet Engine ===

Das simpl4 backend kann auch als WAR in einer Servlet-Engine deployed werden.

[.width700]
imagezoom::web/presentation/images/servlet-engine_de.svg[]


