:linkattrs:
:source-highlighter: rouge


== Technischer Überblick ==


=== simpl4 backend, die wichtigsten Bestandteile ===

[.width800]
imagezoom::web/presentation/images/bigpicture.svg[]

=== Serviceengine ===

Ausführen und steuern von Servicemodellen, erstellt im simpl4 Serviceeditor. +
In diesem Editor können sie auf flexible Weise simpl4 Bausteine miteinander verknüpfen. +
Ein service besteht aus einem oder mehren Bausteinen. +
simpl4 enthält einen großen Baukasten mit fertigen Bausteinen.

[.width800]
imagezoom::web/presentation/images/service.svg[]

==== Exchange ====

Am Serviceeingang wird ein Exchange erstellt und mit den Serviceparametern gefüllt. +
Der Exchange wird von Baustein zu Baustein gereicht.

[.width500]
imagezoom::web/presentation/images/exchange.svg[]

=== Prozess-Engine ===

* Führt die in BPMN definierten Prozessmodelle aus und orchestriert die Service-Engine sowie die Humantasks.
* Die Prozess-Engine bietet die Funktionalität um  Business Process Model and Notation(BPMN) ausführen.
* Ein graphischer Editor(Modellierer) für BPMN2 Prozessmodelle steht in *simpl4* zur Verfügung.
* Serviceaufgaben werden an die service engine delegiert.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registriert bei der IANA.
* Bietet geroutete Remote-Procedure-Calls (RPC) und Publish & Subscribe (PubSub) .
* WAMP ist grob unterteilt in Clients und Router.
* *simpl4* fungiert als  WAMP-Client und  hat  außerdem einen WAMP-Router eingebaut.
* Die in simpl4 definierten Services sind an diesem WAMP-Router registeriert.
* Es können sich externe Geräte (oder auch Browser) ihre Dienste (Prozeduren) registrieren lassen, +
und sind damit von jedem anderen WAMP-Client erreichbar. +
Positiver Nebeneffekt, dadurch ist Browser-to-Browser Kommunikation möglich!


=== Standalone-Server ===

[.width700]
imagezoom::web/presentation/images/server_en.svg[]
