:linkattrs:
:source-highlighter: rouge


== Technical overview ==


=== simpl4 backend, the main ingredients ===

[.width600]
imagezoom::web/presentation/images/bigpicture.svg[]

=== Apache Camel *Routing and conversion engine* ===

* Camelroutes are the main processing units in *_simpl4_.* +
The specify the data flow from component to component. +
A Camel route corresponds to a procedure that registers on the WAMP router and is in this way reachable via RPC(HTTP or websocket).

=== Activiti processengine

* Processes (workflows) are executed in the Activiti processengine.
* The processes are specified in BPMN2.
* A graphical editor (Modeler) is available here.
* Service tasks can be delegated to Camel.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registered by IANA
* Provides routed remote procedure calls (RPC) and PubSub
* WAMP consists of clients and routers (not be confused with the Camel routes)
* The procedures are registered on the router
* *simpl4* is WAMP client and router
* External equipment (or browsers) can register their services (procedures) and thereby are reachable from each other WAMP client. +
Incidentally, in this way is browser-browser communication possible!

=== Standalone server ===

[.width600]
imagezoom::web/presentation/images/server_en.svg[]

=== Servlet engine ===

The simpl4 backend can be deployed as a WAR in a servlet engine.

[.width600]
imagezoom::web/presentation/images/servlet-engine_en.svg[]

