:linkattrs:
:source-highlighter: rouge


== Technical overview ==


=== simpl4 backend, the main ingredients ===

[.width800]
imagezoom::web/presentation/images/bigpicture.svg[]

=== Serviceengine ===

Executes and controls services models created in the simpl4 service editor. +
A service consists of one or more building blocks.

[.width800]
imagezoom::web/presentation/images/service.svg[]

==== Exchange ====

On the service entrypoint an exchange is created and with the service parameters populated. +
The exchange is handed from building block to building block.

[.width500]
imagezoom::web/presentation/images/exchange.svg[]



=== Processengine

=== Processengine

* Executes and coordinates the sequences, that are defined in a process model.
* The process engine provides the capabilities to execute Business Process Model and Notation (BPMN). 
* in simpl4 there is a graphical modeler to create the processes models.
* Service tasks are delegated to the service engine.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registered by IANA.
* Provides routed remote procedure calls (RPC) and Publish & Subscribe (PubSub).
* WAMP is roughly divided into clients and router.
* *simpl4* acts as WAMP client and has  a WAMP router integrated.
* In simpl4 defined services are registered at this WAMP router.
* External equipment (or browsers) can register their services (procedures) and thereby are reachable from each other WAMP client. +
Incidentally, in this way is browser-browser communication possible!

=== Standalone server ===

[.width700]
imagezoom::web/presentation/images/server_en.svg[]


