:linkattrs:
:source-highlighter: rouge

= simpl4==


== Technischer Überblick ==
Die wichtigsten Bestandteile

=== Apache Camel *Routing und Konvertierungs Engine* ===

* Camelrouten sind die hauptsächlichen Verarbeitungseinheiten in *_simpl4._* +
Sie spezifizieren den Datenfluß von Komponente zu Komponente. +
Eine Camelroute entspricht einer Prozedur die sich am WAMP Router registriert und via RPC(über http oder Websocket) erreichbar ist.

=== Activiti Prozessengine ===

Prozese(Workflows) werden in der activiti prozessengine ausgeführt.
Die Prozesse werden in BPMN2 spezifiziert.
Ein Graphischereditor(Modeler) steht hier zur Verfügung.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registriert bei der IANA
* Bietet geroutete Remote-Procedure-Calls (RPC) und PubSub
* WAMP besteht aus Clients und Routern (Nicht verwechseln mit den Camelrouten)
* Am Router sind die Prozeduren registriert
* *_simpl4_* ist WAMP-Client und WAMP-Router
* Es können sich externe Geräte (oder auch Browser) ihre Dienste (Prozeduren) registrieren lassen, und sind damit von jedem anderen WAMP-Client erreichbar. +
Positiver Nebeneffekt, dadurch ist Browser-to-Browser Kommunikation möglich!



[.border.left.thumb.width500]
imagezoom::web/presentation/images/bigpicture.svg[]
