:linkattrs:
:source-highlighter: rouge


== Technischer Überblick ==


=== simpl4 backend, die wichtigsten Bestandteile ===

[.width800]
imagezoom::web/presentation/images/bigpicture.svg[]

=== Service ===

Ein service besteht aus einem oder mehren Bausteinen.

[.width800]
imagezoom::web/presentation/images/service.svg[]

==== Exchange ====

Am Serviceeingang wird ein Exchange erstellt und mit den Serviceparametern gefüllt. +
Der Exchange wird von Baustein zu Baustein gereicht.

[.width500]
imagezoom::web/presentation/images/exchange.svg[]

=== Activiti Prozessengine ===

* Prozesse(Workflows) werden in der activiti prozessengine ausgeführt.
* Die Prozesse werden in BPMN2 spezifiziert.
* Ein graphischer Editor(Modeler) steht hier zur Verfügung.
* Serviceaufgaben werden an die service engine delegiert.

=== WAMP *Web Application Messaging Protocol* ===

* Websocket Subprotokol registriert bei der IANA
* Bietet geroutete Remote-Procedure-Calls (RPC) und PubSub
* WAMP besteht aus Clients und Routern (Nicht verwechseln mit den Camelrouten)
* Am Router sind die Prozeduren registriert
* *simpl4* ist WAMP-Client und WAMP-Router
* Es können sich externe Geräte (oder auch Browser) ihre Dienste (Prozeduren) registrieren lassen, und sind damit von jedem anderen WAMP-Client erreichbar. +
Positiver Nebeneffekt, dadurch ist Browser-to-Browser Kommunikation möglich!


=== Standalone-Server ===

[.width700]
imagezoom::web/presentation/images/server_en.svg[]
