:linkattrs:
:source-highlighter: rouge

= simpl4==

== Various types of processing ==

=== Request-Response (RPC) ===

*The answer should be immediately available.*

* Enabled intergrations rules, configured as RPC-Type  are registered on the link:https://en.wikipedia.org/wiki/Web_Application_Messaging_Protocol[WAMP,window="_blank"]-Router as procedures.
* The procedure parameters and the return value are defined in the WAMP endpoint *(2)*.
* It is therefore possible, provided authorization, to invoke the rule from  WAMP-client(eq.Browser) as service(remote procedure).

[.border.thumb]
image::web/presentation/images/request-response.svg[width=400]

* The response contains the data, that was produced in the last component *(1)* as return value of the procedure.
* *(2)* is both, input and output.

=== Publish / Subscribe ===

*If the publisher released new data, she are immediately visible at all subscriber.*

* A Integration rule can be used as a publisher.
* The WAMP endpoint is configured as publisher type.
* The body of the message contains the publishing data.
* In this example, whenever a file is copied to the "Publish" folder, the subscriber gets immediately the content.

[.border.thumb]
image::web/presentation/images/publish-subscribe.svg[width=400]


=== Starting a process ===

*The execution time of a process can be very long (weeks, months!). +
It is therefore important that the guardian can always retrieve the state of the process.*

* The system stopps after  the three green tasks, +
because the red task is assigned  to another person.
* If that person has executed the red task, the initiator is notified.

[.border.thumb]
imagezoom::web/presentation/images/process1.svg[]
