:linkattrs:

== simpldate (Besprechungen planen) ==

=== Übersicht === 


==== Die Hauptaspekte ====

* Prozess (Mit Sub-Prozess, Message Events und EMail Service Task)
* Service (Implementieren eines RPC Interfaces, was das Zusammenspiel der Serviceengine und der Processengine zeigt)
* Form (Einbinden in die Webseite)
* Webapp (Grundgerüst, eine maßgeschneiderte Form)


[TIP]
In diesem Prozess werden keine Benutzer Tasks verwendet ! +
Es ist nicht möglich, da eine unbekannte Anzahl an Teilnehmern involviert ist, +
die zudem auch keine User in simpl4 sind. +
Deswegen wurden die verwendeten Forms als Webseiten realisiert, und dem Prozess via RPC übergeben.

* InitiateForm (initiate.form) startet den Prozess.
* Die Voting-Seite kommuniziert mit dem Process via RPC (letztendlich wird dem Prozess eine Message gesendet)

--
[.width4000]
imagezoom::web/images/simpldate_overview.svg[border]
--

=== RPC ===


Die Applikation benötigt im Moment 4 RPCs um mit dem Prozess zu kommunizieren. Der Vierte, das
Beenden des Prozesses, muss noch gemacht werden.
Die Service-Komponente "workflow" setzt die "RPCs" um.

* Starten des Prozesses
* Message-Events an Prozess senden
* Variablen (Zustand) des Prozesses auslesen

[.width600]
imagezoom::web/images/camel.svg[]

=== WEB ===

Die Webseiten sind als HTML5-Customelements realisiert.

* simpldate-initiate
* simpldate-vote

