:linkattrs:

=== icon:bars[size=1x,role=black] Übersicht ===

[CI,header="Open-Source- Entwicklungsumgebung"]
simpl4 steht unter der GPLV3 (General Public License) und 
kann daher von jedem kostenlos verwendet werden.
[CI,header="Flexible repsonsive Anwendungen mit HTML5-Frontend für Smartphones, Tablets und Desktops"]
Applikationen einmal erstellen auf allen gängigen Geräten benutzen.
[CI,header="Schnelle Erstellung von Prozessen, Tabellen, Forms ..."]
--
* Geschäftsprozessen (mit BPMN 2.0 Modeller)
* Datenmodell (konfortabler Editor zum Definieren des Datenmodells) 
* Datenbanktabellen (werden automatisch erzeugt, abgeleitet vom Datenmodell) 
* Forms (freidefiniert oder abgeleitet vom Datenmodell)
* Integrationsregeln 
* Geschäftsregeln 
* Datenabfragen
* Dokumenttemplates
--
[CI,header="BPMN 2.0 – Business Process Model and Notation"]
--
is a graphical representation for specifying business processes.
The objective of BPMN is to support business process management, for both technical users and business users, by providing a notation that is intuitive to business users, yet able to represent complex process semantics
--
[CI,header="Business-Process-Engine"]
--
Executes the BPMN process models +
and orchestrates the integration engine and the Human Tasks
--
[CI,header="Regelbasierte Integration-Engine"]
--
Die Integrationsengine verbindet auf flexible Weise simpl4 Bausteine miteinander. +
In einem visuellen Editor werden die Integrationsregeln definiert.
--
[CI,header="Cloud-ready (PaaS,SaaS)"]
simpl4 und simpl4 Applikationen  füllen die Cloud Schichten PaaS und SaaS
[CI,header="Integration bestehender Softwaresysteme"]
-
[CI,header="Entwicklung im Browser"]
-
[CI,header="Minimales Projekt-Setup"]
-
[CI,header="Web Application Messaging Protocol (Websocket Subprotokoll)"]
--
link:https://en.wikipedia.org/wiki/Web_Application_Messaging_Protocol[WAMP,window="_blank"] +
Ist ein offenes Standard WebSocket Subprotokoll und + 
stellt zwei Muster zum Austausch von Nachrichten + 
zwischen Applikationen zur Verfügung.

* Publish/Subscribe (PubSub) 
* Remote Procedure Calls (RPC)
--
[CI,header="Git-basierter simpl4-Application-Store"]
-

[.imageblock.left.width600]
imagezoom::web/images/features2.svgz[]
