:linkattrs:

=== icon:bars[size=1x,role=black] Übersicht ===

[CI,header="Open-Source- Entwicklungsumgebung"]
simpl4 steht unter der GPLV3 (General Public License) und 
kann daher von jedem kostenlos verwendet werden.
[CI,header="Flexible repsonsive Anwendungen mit HTML5-Frontend für Smartphones, Tablets und Desktops"]
Applikationen einmal erstellen auf allen gängigen Geräten benutzen.
[CI,header="Schnelle Erstellung von Prozessen, Tabellen, Forms ..."]
--
* Geschäftsprozessen (mit BPMN 2.0 Modeller)
* Datenmodell (komfortabler Editor zum Definieren des Datenmodells) 
* Datenbanktabellen (werden automatisch erzeugt, abgeleitet vom Datenmodell) 
* Forms (freidefiniert oder abgeleitet vom Datenmodell)
* Servicemodelle 
* Geschäftsregeln 
* Datenabfragen
* Dokumenttemplates
--
[CI,header="BPMN 2.0 – Business Process Model and Notation"]
--
ist eine grafische Spezifikationssprache. 
Sie stellt Symbole zur Verfügung, mit denen Fach- und Informatikspezialisten 
Geschäftsprozesse und Arbeitsabläufe modellieren und dokumentieren können.
--
[CI,header="Business-Process-Engine"]
--
Führt die in BPMN2.0 definierten Prozessmodelle aus +
und orchestriert die Service-Engine sowie die Humantasks.
--
[CI,header="Service-Engine"]
--
Im ServiceEditor wird das Servicemodel definiert,das in der Service-Engine ausgeführt wird. +
In diesem Editor können sie auf flexible Weise simpl4 Bausteine miteinander verknüpfen.
--
[CI,header="Cloud-ready (PaaS,SaaS)"]
simpl4 und simpl4 Applikationen  füllen die Cloud Schichten PaaS und SaaS
[CI,header="Integration bestehender Softwaresysteme"]
-
[CI,header="Entwicklung im Browser"]
-
[CI,header="Minimales Projekt-Setup"]
-
[CI,header="Web Application Messaging Protocol (Websocket Subprotokoll)"]
--
link:https://en.wikipedia.org/wiki/Web_Application_Messaging_Protocol[WAMP,window="_blank"] +
Ist ein offenes Standard WebSocket Subprotokoll und + 
stellt zwei Muster zum Austausch von Nachrichten + 
zwischen Applikationen zur Verfügung.

* Publish/Subscribe (PubSub) 
* Remote Procedure Calls (RPC)
--
[CI,header="Git-basierter simpl4-Application-Store"]
-

[.imageblock.left.width600]
imagezoom::web/images/features.svgz[]
