:linkattrs:

=== icon:bars[size=1x,role=black] Was bietet simpl4? ===


[CI, header="Einfache Installation"]
--
Viele Möglichkeiten der Installation

* Virtualisierung( Images für link:local:resources[VirtualBox und vmware])
* Container (link:local:resources[Docker und LXD])
* link:local:resources[Vagrant] Umgebung
* link:https://github.com/ms123s/simpl4-deployed[Clonen,window="_blank"] eines Repositories von Github
* Selber compilieren
* Testzugang bei uns anfordern
* Wir sind Ihnen auch behilflich bei der Installation bei einem Hoster ihrer Wahl oder in der Cloud(Google, Amazon ..)
--
[CI, header="Website mit vorgebenen Gerüst"]
--
Durch ein vorgebenes Gerüst,ist der Einstieg sehr einfach .

* Tool für Menu und Seitenstruktur
* Theme beliebig anpassbar

Website kann aber auch komplett nach ihren Bedürfnissen aufgebaut werden.
--
[CI, header="Statische und dynamische Webseiten"]
--
mit HTML5 und/oder Markdown(Asciidoc) erstellen. +
Auch Markdown Seiten können dynamischen Inhalt enthalten. +
simpl4 kann als sehr einfach zu handhabendes CMS Verwendung finden.
--
[CI, header="Eingebaute Datenbank"]
--
* Keinerlei Setup.  Datenmodell erstellen und benutzen
* Auch andere Datenbanken(Postgresql, Mysql, Sqlserver, Oracle, DB2  ..) sind einfach integrierbar
--
[CI, header="Viele Scriptsprachen"]
--
Wählen sie aus einer Anzahl von Sprachen aus

* PHP
* Ruby
* Python
* Javascript
* Groovy
* Java8
--
[CI, header="Flexible parametrisierbare Bausteine"]
--
Greifen sie auf einen großen Baukasten mit fertigen Bausteinen(Komponenten) zu. +
Verbindung der Bausteine durch Parametrisierung und/oder Scripting
--
[CI, header="Website komfortabel mit Prozessen verknüpfen"]
--
* Prozesse starten
* ausgewählte Prozessereignisse abonnieren und asynchron über Websocket empfangen
* Human tasks in die Website integrieren.
* Tasklisten abrufen
* Taskstatus setzen
--
[CI, header="Werkzeuge zum Importieren ihrer Daten"]
-
[CI, header="Dynamische Inhalte aus beliebigen Datenquellen."]
-
[CI, header="Flexible Anpassbarkeit an neue Anforderungen"]
--
Die Webseite wächst mit ihren Anforderungen. +
Von statischen Seiten, über das Einbinden von Datenquellen, bis hin zu Businessprozessen, ist alles möglich.
--
[CI, header="Schnelle Entwicklungzyklen"]
--
In den visualisierten Abläufen sind Ansätze für notwendige Programmänderungen einfacher erkennbar
--

[.imageblock.left.width800]
image::web/images/devel.svg[]
