:linkattrs:
:source-highlighter: rouge



== Dataflow


The flow of data from webfront to the backend.


image::docu/images/dataflow/form.svg[]

==== This are the resulting data.

[source,json]
.shown in javascript object notation(JSON)
----
{
  firstname: "Manfred",
  surname: "Sattler"
}

----

Via rpc is the object transferred to the backend. +
The object is declared as the parameter "data".

[source,json]
----
rpcParams = {
	data :{
		firstname: "Manfred",
		surname: "Sattler"
	}
}
----

If we have no other parameter , we can also do this.
[source,json]
----
rpcParams = 
	{
		firstname: "Manfred",
		surname: "Sattler"
	}
----


But in this case , we want send a second parameter.
[source,json]
----
rpcParams = {
	operation: "insert",
	data :{
		firstname: "Manfred",
		surname: "Sattler"
	}
}
----

==== Serviceentrypoint

image::docu/images/dataflow/parameter.svg[]

. The parameter names. 
. We can rename the names. 
. "operation" has a defaultvalue
. and is therefore optional.
. The types.
. The place where the parameters are stored


==== Access in the building block

image::docu/images/dataflow/block.svg[]

. The parameter names. 

. The complete formadata are given to the block
we have put the "data" parameter previously in the properties. +
"p." is a shorthand for properties, therefore you can also use *properties.data* +
If the parameter in the header stored, then you have access with  *h.data* or *headers.data*
