:linkattrs:
:source-highlighter: rouge

=== Legal Disclosure ===

Information in accordance with section 5 TMG

[role="border"] 
--
Responsible for the content of this website:

transparent solutions Software Systems & Consulting GmbH +
Schlesierstraße 15 +
Germany - 91735 Muhr am See

fon: +49 (0)9831 88 47538 +
fax: +49 (0)9831 88 02984

Represented by the CEO: +
Jürgen Roscher und Manfred Sattler

Amtsgericht Ansbach HRB 5377 +
Ust.-Identnr.:DE 192 578 420
--

==== Contact ====

[role="border"] 
--
E-Mail: link:mailto:info@simpl4.org[info@simpl4.org] +
Internetaddress: link:http://simpl4.org[web.simpl4.org]           
--
                                                        
==== Disclaimer ====
                                                        
===== Accountability for content =====
The contents of our pages have been created with the utmost care. However, we cannot guarantee the contents' accuracy, completeness or topicality. According to statutory provisions, we are furthermore responsible for our own content on these web pages. In this context, please note that we are accordingly not obliged to monitor merely the transmitted or saved information of third parties, or investigate circumstances pointing to illegal activity. Our obligations to remove or block the use of information under generally applicable laws remain unaffected by this as per §§ 8 to 10 of the Telemedia Act (TMG). 

===== Accountability for links =====
Responsibility for the content of external links (to web pages of third parties) lies solely with the operators of the linked pages. No violations were evident to us at the time of linking. Should any legal infringement become known to us, we will remove the respective link immediately.

===== Copyright =====
Our web pages and their contents are subject to German copyright law. Unless expressly permitted by law (§ 44a et seq. of the copyright law), every form of utilizing, reproducing or processing works subject to copyright protection on our web pages requires the prior consent of the respective owner of the rights. Individual reproductions of a work are allowed only for private use, so must not serve either directly or indirectly for earnings. Unauthorized utilization of copyrighted works is punishable (§ 106 of the copyright law).


