:linkattrs:

=== Neuigkeiten über und zu simpl4 ===

==== Februar 2016 - Teilen Sie uns und anderen Ihre Fragen mit

Wir haben für Sie ein link:http://simpl4-redmine.ms123.org/projects/simpl4-public?file=start[Issue- Tracking-System,window="_blank"] zu simpl4 einrichtet. Registrieren Sie sich, und erfassen Sie Ihre Anregungen, Fragen und mehr.


==== Februar 2016 - simpl4 bei den Chemnitzer Linuxtagen am 19./20. März 2016

Wir werden mit einem link:https://chemnitzer.linux-tage.de/2016/de/programm/beitrag/372/?file=start[Vortrag,window="_blank"] und einem link:https://chemnitzer.linux-tage.de/2016/de/programm/beitrag/373/?file=start[Workshop,window="_blank"] zu simpl4 vertreten sein.
Weitere Informationen vor Ort erhalten Sie an unserem Stand.


==== Januar 2016 - simpl4 beim Open-Source-Treffen am 22.01.2016 in München

Hier wird ein Einblick in simpl4 gegeben, und kleine Beispiele gezeigt.
link:https://www.opensourcetreffen.de/?file=start[https://www.opensourcetreffen.de/?file=start,window="_blank"]

==== Dezember 2015 - Neue Features in simpl4 

* VFS-Camel Komponente

* Docbook-Camel
Markdown(Asciidoctor) → Pdf
simpl4-Documents → Pdf war bisher nur von Activiti steuerbar, hierfür wurde eine neue Camel-Komponente erstellt. 
Durch die Auslagerung in Camel ist es viel flexibler, man kann dadurch auf einfache Weise Daten in ein Dokument bringen.


==== November 2015 - Erstes offizielle Release von simpl4 steht zur Verfügung

Seit November 2015 steht das erste offizielle Release der Open-Source-Entwicklungsumgebung simpl4 steht unter der GNU General Public Licence v3 zur Verfügung.
Weiterlesen unter link:http://www.heise.de/ix/meldung/simpl4-Neue-Open-Source-Entwicklungsumgebung-mit-geringem-Aufwand-2919699.html[http://www.heise.de/ix/meldung/simpl4-Neue-Open-Source-Entwicklungsumgebung-mit-geringem-Aufwand-2919699.html,window="_blank"]

Sie haben Fragen, kontaktieren Sie uns unter + 
EMail: info@simpl4.org +
Telefon: +49 (0)9831 8847538