:linkattrs:
:source-highlighter: rouge



== Ubuntu bei Hetzner installieren

* Rescuesystem booten und einloggen
* installimage aufrufen
* Neuestes Ubuntu auswählen
* Auskommentieren: DRIVE2, SWRAID*
* HOSTNAME ändern
* PART /boot auskommentieren, 
* Root 20G, ext4
* F10 and go
* Reboot und wieder einloggen
* Schlüssel kopieren
* sshd port nach 2122 änderen
* apt-get update
* apt-get upgrade
* apt-get install ubuntu-server //nicht nötig
* apt-get install python #(für ansible) //wird im deploy Container erledigt 

== ZFS 
```shell
apt-get install zfs
```

==== Disklayout 

sda1 : root 20G
sda2 : Rest zfs

sdb1 : free 20G #maybe swap
sdb2 : Rest zfs

create zpool
```shell
zpool create -o ashift=12 -f zpool  mirror sda2 sdb2 
```

=== Only on C1

```bash
apt-get install ansible
zfs create zpool/gitbucket
cd /zpool/gitbucket
git clone http://gitbucket.ms123.org/git/cloud/hostconfig.git
```

== Der Rest wird mit ansible geregelt

=== Language ===

/etc/locale.gen
```
de_DE.UTF-8 UTF-8
```
```bash
locale-gen
update-locale  LANG=de_DE.UTF-8 LANGUAGE=de
```

=== ipv6 off

*/etc/sysctl.conf*
```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-ip6tables=1
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter=0
net.ipv4.ip_forward=1
```

```bash
sysctl -p
```

=== Vim,Zsh, Utils
```shell
apt-get install git zsh vim mlocate strace tcpdump bridge-utils psmisc net-tools htop dnsutils telnet python tree
```
* zsh in passwd eintragen, 
* vimrc, .vim, zshrc von anderen System kopieren

== SHOREWALL

```bash
apt-get install shorewall
cd  /usr/share/shorewall/configfiles/
cp rules zones interfaces policy masq /etc/shorewall
```

*/etc/default/shorewall*
```
startup=1
```

*masq*
```bash
eth0                    192.168.0.0/16
```

*zones*
```bash
fw  firewall
net ipv4
lxd ipv4
lxc ipv4
```

*interfaces*
```bash
net     eth0
lxd    lxdbr0
lxc    lxcbr0
```

*rules*
```bash
Ping/ACCEPT net     $FW

ACCEPT  net fw tcp  2122

DNAT    net lxd:10.171.101.109:80 tcp  80
DNAT    net lxd:10.171.101.109:443 tcp  443

```

*policy*
```bash
lxd        net     ACCEPT
lxd        $FW     ACCEPT      -
lxd        all     ACCEPT      -

lxc        net     ACCEPT
lxc        $FW     ACCEPT      -
lxc        all     ACCEPT      -

$FW     net     ACCEPT      -
$FW     all     ACCEPT      -

#
# Policies for traffic originating from the Internet zone (net)
#
net     all     DROP        -

# THE FOLLOWING POLICY MUST BE LAST
all     all     REJECT      -

```


```bash
systemctl restart shorewall
systemctl enable shorewall

```





== Openvswitch /OVN

```shell
apt-get install  openvswitch-switch python-openvswitch python-netifaces
apt-get install  ovn-central
apt-get install  ovn-host

systemctl start openvswitch-switch.service
systemctl enable openvswitch-switch.service


```
==== Test openvswitch


```shell

# host c1
REMOTE_IP=138.201.50.73
BRIDGE_ADDRESS=172.16.42.1/24

# host c2
REMOTE_IP=88.99.69.170
BRIDGE_ADDRESS=172.16.42.2/24

#both hosts
LIN_BRIDGE=linbr0
OVS_BRIDGE=ovsbr0

#cleanup from prev runs
ip link set $LIN_BRIDGE down
brctl delbr $LIN_BRIDGE
ovs-vsctl del-br $OVS_BRIDGE

#linux bridge
brctl addbr $LIN_BRIDGE
ip a add $BRIDGE_ADDRESS dev $LIN_BRIDGE
ip link set $LIN_BRIDGE up

#ovs stuff
ovs-vsctl add-br $OVS_BRIDGE
ip link set $OVS_BRIDGE up

# Create the tunnel to the other host and attach it to the $OVS_BRIDGE bridge
ovs-vsctl add-port $OVS_BRIDGE gre0 -- set interface gre0 type=gre options:remote_ip=$REMOTE_IP #options:pmtud=false
#ovs-vsctl add-port $OVS_BRIDGE tun0 -- set interface tun0 type=geneve options:remote_ip=$REMOTE_IP options:key=123
ovs-vsctl set int $OVS_BRIDGE mtu_request=1462 #very urgent!!  1500-$HEADER  GRE=38, GENEVE eg. need more, 49:Empirically determined


# Add the $OVS_BRIDGE bridge to linbr0 bridge
brctl addif $LIN_BRIDGE $OVS_BRIDGE

```


== FLannel

=== etcd on c1

```bash
apt install  etcd
```

===== /etc/default/etcd.conf
```
ETCD_NAME=default
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"
```

```bash
systemctl restart etcd
systemctl enable etcd
```

===== flannel-s10-config.json
```json
{
    "Network": "10.0.0.0/16",
    "SubnetLen": 24,
    "SubnetMin": "10.0.2.0",
    "SubnetMax": "10.0.10.0",
    "Backend": {
        "Type": "vxlan",
        "VNI": 1
     }
}
```

===== flannel-s192-config.json
```json
{
    "Network": "192.168.0.0/16",
    "SubnetLen": 24,
    "SubnetMin": "192.168.2.0",
    "SubnetMax": "192.168.10.0",
    "Backend": {
        "Type": "vxlan",
        "VNI": 2
     }
}
```

```bash
etcdctl set /simpl4.org/network/config < flannel-s10-config.json
etcdctl set /simpl4.org/network/config < flannel-s192-config.json
```

=== install fannel on all hosts
```bash
apt install linux-libc-dev golang gcc
```

==== setting gopath in /etc/zsh/zshrc
```
export GOPATH=/zpool/gopath
```

==== build flannel
```bash
mkdir -p /zpool/gopath/src/github.com/coreos/
cd /zpool/gopath/src/github.com/coreos/
git clone https://github.com/coreos/flannel.git
cd flannel
git checkout v0.7.0
CGO_ENABLED=1 make dist/flanneld
cp dist/flanneld /usr/local/bin
```

==== /etc/default/flanneld
```
# etcd url location.  Point this to the server where etcd runs
FLANNEL_ETCD="http://c1.ms123.org:2379"
#FLANNEL_ETCD_KEY_S10="/simpl4.org/network/s10"
#FLANNEL_ETCD_FILE_S10="s10"
#FLANNEL_OPTIONS=""
```

==== flannel services for every subnet

===== /lib/systemd/system/flanneldS10.service
```
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/flanneld
ExecStart=/usr/local/bin/flanneld -ip-masq=false -subnet-file="/run/flannel/s10.env" -etcd-endpoints=${FLANNEL_ETCD} -etcd-prefix="/simpl4.org/network/s10" 
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
```

===== /lib/systemd/system/flanneldS192.service
```
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/flanneld
ExecStart=/usr/local/bin/flanneld -ip-masq=false -subnet-file="/run/flannel/s192.env" -etcd-endpoints=${FLANNEL_ETCD} -etcd-prefix="/simpl4.org/network/s192" 
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
```

```bash
systemctl daemon-reload
```

==== starting flannel for every subnet

```bash
systemctl restart flanneldS10
systemctl enable flanneldS10

systemctl restart flanneldS192
systemctl enable flanneldS192
```

== LXD ==

```bash
zfs create zpool/lxd
apt-get install lxd
```

=== lxd init
```
lxd init << EOF
zfs
no
zpool/lxd
no
no
yes
lxdnet0
auto
none
EOF
```

=== lxd subnet
```bash
. /run/flannel/s192.env
cat /run/flannel/s192.env
lxc network edit lxdnet0
lxc network set lxdnet0  ipv4.nat false
lxc network set lxdnet0  ipv4.address $FLANNEL_SUBNET
```


=== add flannel interface to lxdnet

```bash
. /run/flannel/s10.env
SUBNET=$( echo "$FLANNEL_SUBNET" | sed "s!\.1/24!!")
SUBNET="${SUBNET}.0"
INTERFACE=$(ifconfig | grep -B1 $SUBNET | grep -o "^flannel\.*[0-9]")

brctl addif lxdnet0 $INTERFACE
```

=== lxd remote usage

.on c2
```bash
lxc config set core.https_address "[::]:8443"
lxc config set core.trust_password ms123
```
.on c3
```bash
lxc config set core.https_address "[::]:8443"
lxc remote add c2 10.0.0.2 #ip c2
```
.on c3, launch a container on c2 with name test1
```bash
lxc launch ubuntu:14.04 c2:test1
```

==== Test Flannel
```bash
# Master c1
BRIDGE_ADDRESS=192.168.5.1/16

# Node c3
#BRIDGE_ADDRESS=192.168.10.1/16

#all nodes and on master too
LIN_BRIDGE=linbr0
FLANNELIF=flannel.1

#cleanup from prev runs
ip link set $LIN_BRIDGE down
brctl delbr $LIN_BRIDGE

#linux bridge
brctl addbr $LIN_BRIDGE
ip a add $BRIDGE_ADDRESS dev $LIN_BRIDGE
ip link set $LIN_BRIDGE up


# Add the $FLANNELIF  to linbr0 bridge
brctl addif $LIN_BRIDGE $FLANNELIF

```
